### PR TITLE
Coverity fixes

### PR DESCRIPTION
**Pull request by ksooo**

### CODE REVIEW

**Comment by Jalle19** [comment]
Thanks a lot, merge when you feel like it.

**Comment by Jalle19** [comment]
We should probably merge this and make a new release before Isengard final is out.

**Comment by ksooo** [comment]
Yep.

**Comment by ksooo** [comment]
@negge this one should go into the next release. 

What about #23? Have you found time to runtime test it? This feature is imo cool, but as I only have 2 tuners actually not that valuable for me. Thus, my priorities are a bit different...

**Comment by Jalle19** [comment]
No I haven't tested it yet, I'm still using Helix at home but once Isengard is released I'll probably update, should make it easier to test.

**Pull request merged**
