### PR TITLE
5.5.0 Add support for recording file size

### PR DESCRIPTION
**Pull request by ksooo**
Implements support for Kodi 19 feature: https://github.com/xbmc/xbmc/pull/17538

**Depends on https://github.com/tvheadend/tvheadend/pull/1332. Please do not merge until the tvheadend PR got merged.**

### CODE REVIEW

**Comment by ksooo** [comment]
Last commit in https://github.com/tvheadend/tvheadend/commits/master was in Nov 2019. Not sure that project is still alive. Sad.

**Comment by phunkyfish** [comment]
Maybe they just finished it...

**Comment by ksooo** [comment]
> Maybe they just finished it...

 Maybe they did, but it seems there would be still a lot of things to do: https://tvheadend.org/issues

**Comment by phunkyfish** [comment]
It’s probably the most widely used backed. A huge shame if true.

**Comment by Flole998** [comment]
It's still alive, I will become a new developer of the project soon and I can take care of your PR then. I know it has taken some time already but please be patient for just a little longer.

**Comment by Flole998** [comment]
I just merged the PR at the Tvheadend Project.

**Pull request merged**
