### PR TITLE
[cmake] remove usage of kodiplatform

### PR DESCRIPTION
**Pull request by olafhering**
This is apparently unused, so remove it to fix build.

Signed-off-by: Olaf Hering <olaf@aepfle.de>

### CODE REVIEW

**Comment by ksooo** [comment]
If that is the fix, please open PRs for all other addons affected. Is this really the way to go?

**Comment by ksooo** [comment]
@olafhering 

```
[kai@Kais-MBP ~/src/github/ksooo/kodi-pvr-addons]$ grep -ri kodiplatform .
./pvr.stalker/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.stalker/CMakeLists.txt:        ${kodiplatform_INCLUDE_DIRS}
./pvr.stalker/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev,
./pvr.sledovanitv.cz/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.sledovanitv.cz/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.sledovanitv.cz/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, libkodiplatform-dev (>= 16.0.0),
./pvr.njoy/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.njoy/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.njoy/CMakeLists.txt:set(DEPLIBS ${kodiplatform_LIBRARIES}
./pvr.njoy/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev
./pvr.hts/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.hts/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.hts/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, libkodiplatform-dev (>= 16.0.0),
./pvr.argustv/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.argustv/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.argustv/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, libkodiplatform-dev (>= 16.0.0),
./pvr.teleboy/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.teleboy/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.teleboy/CMakeLists.txt:set(DEPLIBS ${kodiplatform_LIBRARIES} 
./pvr.teleboy/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, pkg-config, libkodiplatform-dev (>= 17.1),
./pvr.vdr.vnsi/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.vdr.vnsi/CMakeLists.txt:                    ${kodiplatform_INCLUDE_DIRS}
./pvr.vdr.vnsi/debian/control:               libkodiplatform-dev (>= 17.1.0), kodi-addon-dev,
./pvr.wmc/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.wmc/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.wmc/CMakeLists.txt:set(DEPLIBS ${kodiplatform_LIBRARIES}
./pvr.wmc/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, libkodiplatform-dev (>= 17.1.0),
./pvr.iptvsimple/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.iptvsimple/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.iptvsimple/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, libkodiplatform-dev (>= 16.0.0),
./pvr.zattoo/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.zattoo/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.zattoo/CMakeLists.txt:set(DEPLIBS ${kodiplatform_LIBRARIES} 
./pvr.zattoo/CMakeLists.txt:set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -DZATTOO_VERSION=${ZATTOO_VERSION} -DKODI_VERSION=${kodiplatform_VERSION}")
./pvr.zattoo/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, pkg-config, libkodiplatform-dev (>= 17.1),
./pvr.octonet/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.octonet/CMakeLists.txt:	${kodiplatform_INCLUDE_DIRS}
./pvr.octonet/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev
./pvr.vuplus/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.vuplus/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.vuplus/CMakeLists.txt:set(DEPLIBS ${kodiplatform_LIBRARIES}
./pvr.vuplus/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev,
./pvr.hdhomerun/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.hdhomerun/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.hdhomerun/CMakeLists.txt:set(DEPLIBS ${kodiplatform_LIBRARIES}
./pvr.hdhomerun/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, libkodiplatform-dev (>= 16.0.0),
./pvr.demo/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.demo/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.demo/CMakeLists.txt:set(DEPLIBS ${kodiplatform_LIBRARIES}
./pvr.demo/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev
./pvr.mediaportal.tvserver/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.mediaportal.tvserver/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.mediaportal.tvserver/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev
./pvr.dvblink/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.dvblink/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.dvblink/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev
./pvr.vbox/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.vbox/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.vbox/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev
./pvr.mythtv/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.mythtv/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.mythtv/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, libkodiplatform-dev (>= 16.0.0),
./pvr.dvbviewer/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.dvbviewer/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.dvbviewer/CMakeLists.txt:set(DEPLIBS ${kodiplatform_LIBRARIES}
./pvr.dvbviewer/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, libkodiplatform-dev (>= 17.1.0),
./pvr.nextpvr/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.nextpvr/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.nextpvr/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev
./pvr.pctv/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.pctv/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.pctv/debian/control:Build-Depends: debhelper (>= 9.0.0), cmake, libkodiplatform-dev (>= 16.0.0),
./pvr.filmon/CMakeLists.txt:find_package(kodiplatform REQUIRED)
./pvr.filmon/CMakeLists.txt:include_directories(${kodiplatform_INCLUDE_DIRS}
./pvr.filmon/debian/control:               libkodiplatform-dev (>= 16.0.0), kodi-addon-dev, libjsoncpp-dev
[kai@Kais-MBP ~/src/github/ksooo/kodi-pvr-addons]$ 
```

hmm.

**Comment by olafhering** [comment]
> If that is the fix, please open PRs for all other addons affected. Is this really the way to go?

The question, for which I found no answer myself yet, is: what is kodiplatform good for, if no addone really makes any use of it? There are one or two which misuse it just to get the Kodi version, which is already availabe in kodi-devel itself.

So, please enlight me.

**Comment by ksooo** [comment]
I have no idea, not invented here. Just want to mention if this is the right fix (which well can be the case), you need to open PRs for all (!) affected addons. See the list I posted, but this is just PVR - no idea what else is affcted.

**Comment by ksooo** [comment]
This does not fix the build errors, btw (as you might have seen already): https://travis-ci.org/kodi-pvr/pvr.hts/builds/524464001

**Comment by olafhering** [comment]
Just rebuild it once the base system is fixed again.

**Comment by Rechi** [comment]
Removing `libkodiplatform-dev` in `debian/control` is missing.

**Comment by olafhering** [comment]
Fixed

**Pull request closed without merging**
