### PR TITLE
Replace logo with current tvh logo

### PR DESCRIPTION
**Pull request by dkonerma**
Time to introduce the current logo?

### CODE REVIEW

**Comment by ksooo** [comment]
Have you asked the tvheadend project for permission to use this logo?

**Comment by dkonerma** [comment]
Will check with them (guess it's no problem since the current logo was also tvh's).

**Comment by dkonerma** [comment]
Just received feedback on irc hts; no problem, logo is free to use, see bottom of thread http://tvheadend.org/news/63

**Comment by perexg** [comment]
Ack from my side..

**Comment by ksooo** [comment]
Cool, thanks.

**Comment by ksooo** [comment]
> If you could bump the addon version and add a changelog entry that would be great!

Not needed. I will come up with a PR the very next days. This PR includes version bump and changelog. Let's add the logo change to that PR.

**Comment by Jalle19** [comment]
Okay, feel free to merge then @ksooo

**Pull request merged**
