### PR TITLE
Timeshift: Seeking fixes

### PR DESCRIPTION
**Pull request by perexg**
Cherry picked changes from PR #146 . I've not tested compilation on my dev platform (using 15.2), so little tweaking may be required.

Note: Test with TVH v4.1-1264-g0f069c7 and later.
Note2: Another bunch of timeshift fixes TVH v4.1-1276-ga27ed2e (mainly wrong refcounting and reworked on-demand mode).
Note3: TVH v4.1-1299-g80a50ce seems to catch all major timeshift bugs.

### CODE REVIEW

**Comment by Glenn-1990** [comment]
Did some tests and it seems working better than before ;-)

@ksooo, shouldn't there be time-shift indicators present in the GUI? I thought that this was implemented in Jarvis but I can't see them.
Also It's not possible to forward/rewind time-shift when there is no epg info, a critical bug in kodi? :s

**Comment by ksooo** [comment]
> Did some tests and it seems working better than before ;-)

Cool. Could you please elaborate what "better" means. Especially, what does not yet work?

> shouldn't there be time-shift indicators present in the GUI? I thought that this was implemented in Jarvis but I can't see them.

 Core (incl. pvr.hts) support was implemented for Jarvis, but no Confluence UI. There was a lengthy discussion in the forum about that and people did not like what @FernetMenta proposed and "decided" to live with nothing instead of something semi-optimal (from their POW). I like what Fernet proposed and use it with my private Jarvis build for months, btw. => You may want to give https://github.com/ksooo/xbmc/commits/timeshift-confluence a try.

> Also It's not possible to forward/rewind time-shift when there is no epg info, a critical bug in kodi?

 Sounds strange. No idea. Not my area of expertise, sorry.

**Comment by Jalle19** [comment]
> Sounds strange. No idea. Not my area of expertise, sorry.

It's true, it's been like that since forever.

**Comment by Jalle19** [comment]
Tested with tvheadend 4.0.8, skipping now works reliably. There's still some issues with fast-forwarding/rewinding but I haven't tried tvheadend 4.1 yet so that could be a non-issue too. I suggest we merge this.

**Comment by ksooo** [comment]
> Tested with tvheadend 4.0.8, skipping now works reliably. 

 Also tested with 4.0.8. What shall I say? I was timeshifting and the first skip forward I did (no stop before), led to a hang of kodi. :-/

**Comment by Jalle19** [comment]
That's weird. On-demand disabled?

**Comment by ksooo** [comment]
Yep. Also RAM for buffer is disabled (if this makes a difference).

But looking at the tons of changes and fixes @perexg currently makes on tvh master for the timeshift code and as he wrote that one should test against very latest tvh 4.1 I do not wonder that 4.0.8 does not really work.

**Comment by Glenn-1990** [comment]
@perexg tvh master seems completely broken now, tvh will hang when using timeshift?

**Comment by perexg** [comment]
Many timeshift related changes are in tvh master - things are stable in my testing environment. I might probably backport the timeshift changes to 4.0.x tree, but I'd like to test it more intensively before.

**Comment by Jalle19** [comment]
@ksooo do you mind trying again? It never crashed/froze for me. If it does freeze, can you check with gdb where it does it?

**Comment by ksooo** [comment]
Not sure whether it is actually worth testing against 4.0.x before stuff got backported.

**Comment by perexg** [comment]
Just a note: TVH v4.1-1299-g80a50ce seems to catch all major timeshift bugs.

**Comment by ksooo** [comment]
> Just a note: TVH v4.1-1299-g80a50ce seems to catch all major timeshift bugs.

 In combination with the pvr.hts fixes of this PR, I guess. Which Kodi version are you using for testing? Latest Jarvis beta?

**Comment by perexg** [comment]
No, 15.2 and code from PR #144 . But it should be fine to use also this cherry-picked code from this PR. All changes just throws 'obsoleted' packets received between request / response states. And, the wait call in CHTSPDemuxer::Seek was really broken (missing variable initialization).

**Comment by perexg** [comment]
Another "critical" timeshift bug fixed in v4.1-1301-g25b2cbc .

**Comment by perexg** [comment]
Cross-linking TVH bug (Jarvis testers): https://tvheadend.org/issues/2744

**Comment by Jalle19** [comment]
@perexg can you rebase?

**Comment by CvH** [comment]
Any news on this ? @perexg

**Comment by perexg** [comment]
OK, rebased..

**Pull request merged**
