### PR TITLE
debian packaging: provide transitional package for deprecated kodi-pvr-tvheadend-hts

### PR DESCRIPTION
**Pull request by Jalle19**
Backport to Isengard.

@wsnipex is the package versioning correct?

### CODE REVIEW

**Comment by wsnipex** [comment]
seems to need to rebase, version was already bumped. Otherwise its fine

**Comment by Jalle19** [comment]
@wsnipex yeah it seems I based it on an old head. Can you check again, I bumped the version one notch.

**Comment by wsnipex** [comment]
looks good

**Comment by Jalle19** [comment]
So now the stable PPA needs updating and we're good?

**Pull request merged**
