### PR TITLE
Ignore the auto-generated addon.xml file

### PR DESCRIPTION
**Pull request by Jalle19**

### CODE REVIEW

**Comment by Jalle19** [comment]
@Montellese this is correct right?

**Comment by Montellese** [comment]
Yes if you do an in-tree build.

**Comment by Jalle19** [comment]
@Montellese what other types of builds are there?

**Comment by Montellese** [comment]
AFAIK in-tree builds only work on linux for linux. For anything else we do out-of-tree builds where the generated files are in a different directory than the checked out addon files/code.

**Comment by Jalle19** [comment]
Okay, but either way this file should never be checked in to git right?

**Comment by Montellese** [comment]
Yes.

**Pull request merged**
