### PR TITLE
Settings fixes

### PR DESCRIPTION
**Pull request by Glenn-1990**
As title

### CODE REVIEW

**Comment by Jalle19** [comment]
+1, @ksooo

**Comment by ksooo** [comment]
Please add a changelog entry to tell people about the fixes and I'm fine with this PR.

**Comment by ksooo** [comment]
@Glenn-1990 changelog for 2.2.10 is the correct one, not 2.2.9

**Comment by Glenn-1990** [comment]
@ksooo 
rebased

**Pull request merged**
