### PR TITLE
Fix pointer to freed memory in EPG_TAG.strFirstAired.

### PR DESCRIPTION
**Pull request by ksooo**
Fixes a regression introduced by #445

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
👍

**Comment by ksooo** [comment]
Sorry, this is nonsense. The member was there before this PR, as the diff clearly shows.

**Comment by ksooo** [comment]
You need to update the Kodi code you are trying to compile the add-on with. There was an incompatible Kodi API change recently.

**Comment by nkichukov** [comment]
I missed your comments. I did not realize this declaration is coming from kodi includes. I will research and if I manage to identify what changed I can cherry pick into the branch I am using for my kodi platform. Thanks @ksooo

**Pull request merged**
