### PR TITLE
Backport applicable fixes to Jarvis

### PR DESCRIPTION
**Pull request by Jalle19**
Runtime testing this at the moment, seems to work just fine.

### CODE REVIEW

**Comment by ksooo** [comment]
Jarvis? Really? ;-)

**Comment by Jalle19** [comment]
It's still the currently stable version of Kodi, at leasy according to kodi.tv :-)

**Comment by Jalle19** [comment]
I also tagged all master and Krypton releases by the way

**Comment by Jalle19** [comment]
Watching TV and recordings seems to work, will still need to test manipulating timers etc. before we can consider merging this.

**Comment by Jalle19** [comment]
Been working fine so far, will probably merge this week.

**Comment by ksooo** [comment]
@Jalle19 Can we close this one?

**Comment by Jalle19** [comment]
Do you want to close it or merge it? I'm fairly certain that it works because I've been using it locally for some time, but at the same time I'm a bit afraid of breaking old installations that aren't even supported anymore.

**Comment by ksooo** [comment]
Have no strong opinion on this, just asking in case ot is obsolete. What was Jarvis again? ;-)

**Comment by Jalle19** [comment]
IMO let's merge and see what happens

**Comment by ksooo** [comment]
your button

**Comment by ksooo** [comment]
wow, that was fast :-)

**Pull request merged**
