### PR TITLE
Lower required HTSP version to 10 (allows tvh 3.4 again).

### PR DESCRIPTION
**Pull request by ksooo**
@Jalle19 mind taking a look

### CODE REVIEW

**Comment by ksooo** [comment]
BTW, 18 comes from Timerec support.

**Comment by Jalle19** [comment]
Thanks, looks good.

**Comment by ksooo** [comment]
@Jalle19 Okay. Your button.

**Comment by ksooo** [comment]
@Jalle19 mind if I merge this?

**Comment by Jalle19** [comment]
I'm free tomorrow so I can do a new release etc., but if you're in a hurry then by all means.

**Comment by ksooo** [comment]
This has time until tomorrow. So, please take over.

**Comment by ksooo** [comment]
@Jalle19 this should go into the Isengard branch as well, right?

**Comment by ksooo** [comment]
Or must I create a seperate PR for Isengard?

**Comment by Jalle19** [comment]
Shit, I was in a hurry and forgot about that. Don't worry, I'll fix it.

**Comment by Jalle19** [comment]
I rebased Isengard on master now.

**Pull request merged**
