### PR TITLE
Add support for RDS data contained in AAC streams

### PR DESCRIPTION
**Pull request by ksooo**
Motivation: https://forum.kodi.tv/showthread.php?tid=336682&pid=3052210#pid3052210

This brings back RDS data for NDR, MDR, BR, RBB in Kodi.

Thanks to @carsten-gross for figuring out the details.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Cool :+1:, always like to have RDS further supported and continued.

**Comment by ou-li** [comment]
👍 Works like a charm!

**Comment by ou-li** [comment]
Hi @ksooo ,

there seems to be a little  issue with NDR channels.
According to Carsten, NDR uses extra DSE 0xbc, 0xc0, 0x00 which can be ignored.
They also split RDS frames on several DSE packets:
https://github.com/carsten-gross/FFmpeg/blob/37f926d9be9cfcb78f07e8bb529c0508caf6c39c/libavcodec/aacdec_template.c#L1393

For instance, Kodi did not display any RDS for the following test programme:

[ndr2_test_1815-NDR 2 NDS2021-11-1518-15.zip](https://github.com/kodi-pvr/pvr.hts/files/7589830/ndr2_test_1815-NDR.2.NDS2021-11-1518-15.zip)

[ndr2_rds_ts2shout.txt](https://github.com/kodi-pvr/pvr.hts/files/7589843/ndr2_rds_ts2shout.txt)

Bye for now

**Comment by ksooo** [comment]
@ou-li Please ensure to use at least pvr.hts 19.0.2 (Matrix) or 20.1.1 (Nexus). The problem was recently fixed.

**Comment by ou-li** [comment]
Sorry, my bad, should have checked the version number first, of course.
My LibreElec installation has automatically updated pvr.hts, so everything is fine!

Thx again!

**Pull request merged**
