### PR TITLE
Implement PVR API 5.1.0

### PR DESCRIPTION
**Pull request by ksooo**
Refer to xbmc/xbmc#9290 and xbmc/xbmc#9295 for details.

@FernetMenta demuxer changes good to go?
@Jalle19 good to go?

### CODE REVIEW

**Comment by ksooo** [comment]
@MilhouseVH could you do a runtime test?

**Comment by FernetMenta** [comment]
@ksooo demuxer changes look ok but runtime test is more important in this case.

**Comment by ksooo** [comment]
Hmm. Sounds like a general problem, not only pvr.hts related. Whatever you guys say makes sense.

I only would like to avoid another API bump right now. Regardless of the version number it's always PITA and I really would like somebody else to do the next monkey work, then.

**Comment by ksooo** [comment]
Wouldn't proper <code>memset</code> before reassigning stream data in <code>ParseSubsriptionStart</code>solve the problem @Jalle19 mentioned?

**Comment by Jalle19** [comment]
Yes a `memset()` would fix work, I just don't like polluting the code with C-isms just because we have a C API.

**Comment by ksooo** [comment]
> Yes a memset() would fix work, I just don't like polluting the code with C-isms just because we have a C API.

 Fair enough. For **now** I would like to go with the memset approach. Okay?

**Comment by MilhouseVH** [comment]
> @MilhouseVH could you do a runtime test?

To be honest I don't personally use any PVR functionality so runtime testing is difficult. I can build test it, that's about it - I leave runtime testing to the test users. :)

**Comment by ksooo** [comment]
... now with memset.

**Comment by ksooo** [comment]
Runtime tested. Works to some extend. One can watch tv, but on some channels audio stops after 3-5 seconds. Don't think this is an add-on problem.

@Jalle19 I suggest to merge this PR as it is now, so we have at least a compatible add-on again. Okay?

**Comment by ksooo** [comment]
> I just don't like polluting the code with C-isms just because we have a C API.

 Lets fix this with the next API bump, which I'm pretty sure will come up before Krypton release anyway.

@Jalle19 okay to merge?

**Comment by Jalle19** [comment]
Yeah go ahead, no point in having a broken addon.

**Pull request merged**
