### PR TITLE
Update to libp8-platform

### PR DESCRIPTION
**Pull request by hudokkow**
Supersedes https://github.com/kodi-pvr/pvr.hts/pull/154
Builds with cmake and debuild. Not runtime tested.

### CODE REVIEW

**Comment by Jalle19** [comment]
@ksooo any objections?

**Comment by hudokkow** [comment]
It's the only add-on missing it, ehehe!
Completely forgot about it because of https://github.com/kodi-pvr/pvr.hts/pull/154

**Comment by ksooo** [comment]
@Jalle19 +1. your button

**Comment by Jalle19** [comment]
This should fix the Travis badge, it's been red for a while now. Thanks @hudokkow !

**Pull request merged**
