### PR TITLE
Add support for epg subtitle (episode name).

### PR DESCRIPTION
**Pull request by ksooo**
Latest tvheadend supports epg subtites (episode names):
https://github.com/tvheadend/tvheadend/commit/8dbc38df4a5cd85be243e77e1ebdd43dfe6e2683

### CODE REVIEW

**Comment by Jalle19** [comment]
The "not supported by tvh" comment should be dropped.

**Comment by ksooo** [comment]
oops.

**Comment by ksooo** [comment]
@Jalle19: I have some time today to get the new release out. I think we should include all open PRs except the predictive tuning stuff. Okay?

**Comment by Jalle19** [comment]
Go ahead, that was my intention too.

**Pull request merged**
