### PR TITLE
Fix for  #135

### PR DESCRIPTION
**Pull request by Glenn-1990**
https://github.com/kodi-pvr/pvr.hts/issues/135

### CODE REVIEW

**Comment by ksooo** [comment]
Cool, but can you please elaborate **why** this fixes things?

**Comment by Glenn-1990** [comment]
void SendSubscribe(uint32_t channelId = 0, uint32_t weight = SUBSCRIPTION_WEIGHT_NORMAL, bool restart = false);

Looking to the function declaration, "restart" is the 3rd parameter. 
So we also have to pass the 2 first parameters (which will be ignored anyway), otherwise our boolean will be assigned to the first parameter "channelId"...

**Comment by Jalle19** [comment]
Good catch! This is why I hate methods with many edge-case parameters, makes it easy to do mistakes like this. Too bad the compiler didn't catch it.

**Comment by ksooo** [comment]
What do you guys think about removing the default parameters from declaration of SendSubscribe?

**Comment by Glenn-1990** [comment]
@ksooo yea, that will prevent similar mistakes in the future
PR updated ;-)

**Comment by Jalle19** [comment]
Sounds good to me

**Comment by Jalle19** [comment]
By the way @Glenn-1990 if you want to you can add your name to https://github.com/kodi-pvr/pvr.hts/blob/master/pvr.hts/addon.xml.in#L6, I think you've done enough to warrant having your name there ;-)

**Comment by ksooo** [comment]
> By the way @Glenn-1990 if you want to you can add your name to ...

Definitely a +1 from me for this. :-)

**Pull request merged**
