### PR TITLE
Predictive tuning fixes

### PR DESCRIPTION
**Pull request by Glenn-1990**
Found some issues with predictive tuning when working on the subscription conflict stuff.

### CODE REVIEW

**Comment by Jalle19** [comment]
Can you edit the change log in a separate commit? I think we're already midversion so no need to bump it.

**Comment by ksooo** [comment]
Can you do me a favor and make both the PR title and the commit messages more meaningful. Thx

**Comment by Glenn-1990** [comment]
updated

**Comment by ksooo** [comment]
Looking good now. Thanks a lot.

**Comment by ksooo** [comment]
@Glenn-1990 could you please rebase? Otherwise I cannot merge.

**Comment by Glenn-1990** [comment]
@ksooo done

**Comment by ksooo** [comment]
@Jalle19 any objections?

**Comment by Jalle19** [comment]
Fine by me

**Pull request merged**
