### PR TITLE
Revert version check for Isengard

### PR DESCRIPTION
**Pull request by Jalle19**
@ksooo perhaps this is the best solution for now? You said it yourself, it was only in preparation for J**** features anyway.

### CODE REVIEW

**Comment by ksooo** [comment]
I dont think we should revert. It's working fine with 2.1.10 with the only glitch that it nerves with kaitoasts if tvheadend server is down, which is a very special situation IMO. Fix for this is trivial and already in the queue (https://github.com/ksooo/pvr.hts/commits/fix-htsp-version-check). Just need to test this (extensively) this evening when I'm back home before I open the PR.

**Comment by ksooo** [comment]
... and I do really very sorry for the trouble I've caused with this. ;-/

**Comment by Jalle19** [comment]
Fixing it is fine by me, although I'm going away for a few days now so you're on your own.

**Comment by ksooo** [comment]
np. Will take care.

**Comment by ksooo** [comment]
Just one question: How do you manage to get one PR into both master and Isengard branch without doing a second PR for Isengard branch? 'git merge' in a shell or is there some github support for this?

**Comment by Jalle19** [comment]
You can cherry pick the commits locally as long as the diff is compatible.

**Comment by ksooo** [comment]
... you mean it is okay to directly work on the kodi-pvr/pvr.hts repo for this case; to push the cherry pick directly to kodi-pvr/pvr.hts? I know that this will work as I have the needed access rights for this repo, just asking beause we're generally not doing this (in favour to PRs).

**Comment by Jalle19** [comment]
You can cherry pick locally to a branch based of Isengard, then PR that. I don't really have a preference between pushing and PRing.

**Comment by ksooo** [comment]
As discussed, we're going to fix this for Isengard.

**Pull request closed without merging**
