### PR TITLE
[CI] add appveyor win32 building

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
/me takes a whip and send @hudokkow to work ;)  (just kidding of course)

**Comment by MartijnKaijser** [comment]
Hmm one thing i see that it references the person who added the appvoyer and not the actual repo
(https://ci.appveyor.com/project/MartijnKaijser/pvr-hts-hr8p4)
Seems we need some "project" and not a person

**Comment by MartijnKaijser** [comment]
might still need some tweaking so best wait a bit to add it to all

**Comment by hudokkow** [comment]
Yeap, I was thinking the same. Lets test this one and make it perfect (TM).

**Comment by MartijnKaijser** [comment]
I had to create a new github user as it was running on my own account. Travis at least supports teams/organisations while appveyor runs on the user itself (who can add teams/users to his account).
Some further improvements can be found here https://github.com/AchimTuran/adsp.biquad.filters/tree/ci-builds

**Comment by hudokkow** [comment]
Same with codacy. First pull repo than transfer it to team. Odd workflow.

**Comment by MartijnKaijser** [comment]
Well this one you can't even transfer (couldn't find it)

**Pull request merged**
