### PR TITLE
remove obsolete 'ptr_fun' call within p8-platform and make debian package test on Travis CI

### PR DESCRIPTION
**Pull request by AlwinEsch**
Related to fix p8-platform build on newer C++17.

Error before:
```
[ 17%] Performing build step for ‘p8-platform’
[ 50%] Building CXX object CMakeFiles/p8-platform.dir/src/util/StringUtils.cpp.o
/Users/kai/src/github/ksooo/xbmc/tools/depends/target/binary-addons/macosx10.15_x86_64-target-debug/build/p8-platform/src/p8-platform/src/util/StringUtils.cpp:456:69: error: 
   no member named ‘ptr_fun’ in the global namespace
 str.erase(str.begin(), ::find_if(str.begin(), str.end(), ::not1(::ptr_fun(isspace_c))));
                                 ~~^
/Users/kai/src/github/ksooo/xbmc/tools/depends/target/binary-addons/macosx10.15_x86_64-target-debug/build/p8-platform/src/p8-platform/src/util/StringUtils.cpp:469:58: error: 
   no member named ‘ptr_fun’ in the global namespace
 str.erase(::find_if(str.rbegin(), str.rend(), ::not1(::ptr_fun(isspace_c))).base(), str.end());
                            ~~^
2 errors generated.
make[7]: *** [CMakeFiles/p8-platform.dir/src/util/StringUtils.cpp.o] Error 1
make[6]: *** [CMakeFiles/p8-platform.dir/all] Error 2
make[5]: *** [all] Error 2
make[4]: *** [build/p8-platform/src/p8-platform-stamp/p8-platform-build] Error 2
make[3]: *** [CMakeFiles/p8-platform.dir/all] Error 2
make[2]: *** [CMakeFiles/pvr.hts.dir/rule] Error 2
make[1]: *** [pvr.hts] Error 2
```

### CODE REVIEW

**Comment by lrusak** [comment]
why not use the patch that was merged upstream? https://github.com/Pulse-Eight/platform/commit/a0d1a41ac47930a3d45020d1a8d26b90d3856ce9

**Comment by AlwinEsch** [comment]
Started now to create a request to there.

**EDIT** Thought to ask @ksooo (on slack) that this works on his Mac.

**Comment by ksooo** [comment]
I think we should just use the fixed p8-platform, like @lrusak suggested. That's it.

**Comment by wsnipex** [comment]
if we use p8-platform, we also need a new release of it. Otherwise all linux distros need to carry the patch...

**Comment by ksooo** [comment]
> if we use p8-platform, we also need a new release of it. 

The fix was already merged into p8-platform master. https://github.com/Pulse-Eight/platform/commits/master

**Comment by AlwinEsch** [comment]
Thought also to use from original, but we have differences now between them and our.
Can take the two patches to bring to our fork on https://github.com/xbmc/platform/pull/6

But e.g. here https://packages.ubuntu.com/source/groovy/p8-platform takes the original (with the last release version).

**Comment by emveepee** [comment]
I made this change for testing with pvr.nextpvr https://github.com/emveepee/platform/commit/4016b39b3ab1709f60befc1e9b73725f9471e62d  and it doesn't require xcode12 @phunkyfish  said I shouldn't try and update platform but if it is going to be updated anyway then pvr.hts might not need to force it

**Comment by AlwinEsch** [comment]
No, the xcode12 was only for test purposes, to make sure it works also on latest :smile:.
With the way from p8-platform (and on your) not work with xcode10.2 by Travis, but with way I taken from original https://github.com/xbmc/xbmc/blob/master/xbmc/utils/StringUtils.cpp#L478 does it work :smirk:

**Comment by emveepee** [comment]
> 
> 
> No, the xcode12 was only for test purposes, to make sure it works also on latest 😄.
> With the way from p8-platform (and on your) not work with xcode10.2 by Travis, but with way I taken from original https://github.com/xbmc/xbmc/blob/master/xbmc/utils/StringUtils.cpp#L478 does it work 😏

It seemed to pass CI here https://github.com/kodi-pvr/pvr.nextpvr/pull/148  what didn't I check?

**Comment by AlwinEsch** [comment]
Thats the stupid error within Travis (.org version) or in github and why I come so much times with ask for access there :imp:.

Since few months does travis-ci.org no more report his builds to github by "kodi-pvr". The builds are still done only then need to open his website to see :cry:.

Look here about pvr.nextpvr https://travis-ci.org/github/kodi-pvr/pvr.nextpvr

**Comment by emveepee** [comment]
> 
> 
> Thats the stupid error within Travis (.org version) or in github and why I come so much times with ask for access there 👿.
> 
> Since few months does travis-ci.org no more report his builds to github by "kodi-pvr". The builds are still done only then need to open his website to see 😢.
> 
> Look here about pvr.nextpvr https://travis-ci.org/github/kodi-pvr/pvr.nextpvr

Thanks it make sense now, I missed those 2 new patches. The question remains why not update platform.git and just update p8-platform.txt in all impacted binary addons.  If it really is a question about the shallow clone using master or as hash, create a new branch and we can pull by a tagged filename.

**Comment by AlwinEsch** [comment]
Would make more sense to bring in there.
Will update my request "https://github.com/xbmc/platform/pull/6" later today.

Would be good in the original, but would take too long with all the other things.

In addition, I will look further at the addons, where the p8 platform can be got rid of.

**Comment by emveepee** [comment]
> 
> 
> Thats the stupid error within Travis (.org version) or in github and why I come so much times with ask for access there 👿.

I don't know travis.yml but is there a way to add a test for gcc 7 on xenial  since Kodi supports it?

**Comment by AlwinEsch** [comment]
I think no, as Ubuntu have on Xenial only 5.3.1 (https://packages.ubuntu.com/xenial/gcc), maybe if we add a own created to our launchpad can it work and Travis makes before a `sudo apt ...`, but not sure how far that touch the system.

**Comment by wsnipex** [comment]
I repeat: linux distros use upstream p8-platform and usually only released versions.

**Comment by ksooo** [comment]
@AlwinEsch we can close this PR, right?

**Comment by AlwinEsch** [comment]
Yes after the p8-platform goes away, is it no more needed.

**Pull request closed without merging**
