### PR TITLE
fix install path

### PR DESCRIPTION
**Pull request by mdeguzis**
This also affects Krypton. After view, please merge into the Krypton branch as well.

### CODE REVIEW

**Comment by Jalle19** [comment]
Why do you want to do this? It doesn't look right.

**Comment by mdeguzis** [comment]
Source needs the Kodi piece, but use lib as destination. Sorry, will fix and squash the commits.

**Comment by Jalle19** [comment]
@wsnipex is this correct?

**Comment by wsnipex** [comment]
yes, that is ok

**Pull request merged**
