### PR TITLE
Isengard: muxer - flush the queued packets with wrong pts on seek

### PR DESCRIPTION
**Pull request by perexg**
(only for Isengard branch)

### CODE REVIEW

**Comment by perexg** [comment]
Found another issue - see commit ccf7569c5dbc4115fcbd6aff565a844e884c9596 .

**Comment by perexg** [comment]
Found another fatal error in Seek() - see ec37c7b9e26b5f0e2c063537f7215b37f9b65b84 .

**Comment by Jalle19** [comment]
Can you change the PR to point against master directly from Github, or does it not apply cleanly?

**Comment by ksooo** [comment]
Do we still care about Isengard? Jarvis is to be released soon.

**Comment by perexg** [comment]
The commit 4793806196aa0e8118851e1f510d6e62227731ec shows the purpose. Also, Flush() should be called on rewind or FF 4x + .

**Comment by Glenn-1990** [comment]
Why is this only for Isengard? 
Isengard will be obsolete soon as jarvis is almost in RC.

**Comment by perexg** [comment]
Sorry, I work only with precompiled binaries (using kodi 15.2 package in Fedora). The packaing is always delayed a bit.

**Comment by Jalle19** [comment]
Are all these changes part of #155?

**Comment by perexg** [comment]
Yes, they're.

**Comment by Jalle19** [comment]
Okay. @ksooo do we close this or do you want to make a new release for Isengard with applicable backported patches? I believe OE users would get the update since they use a repository for PVR addons.

**Comment by ksooo** [comment]
What is Isengard? ;-) I do not see a need for an Isengard update- If you ask me, I would close this PR.

**Comment by opdenkamp** [comment]
That you don't see the need doesn't mean that it's not useful for others. Not everyone is using the latest greatest version number :)

**Comment by ksooo** [comment]
That's why I said "if you ask me". ;-) If others don't share my point of view, I'm fine with this'll I will not block an Isengard update.

**Comment by opdenkamp** [comment]
I've merged in PRs for older releases quite often when people sent updates. Only thing that needs to be taken care of is that you bump the add-on version numbers properly if the APIs or ABIs are incompatible, so you don't get clashes.

**Comment by Jalle19** [comment]
@seo will you accept addon bumps for OE 6 even though Isengard development has stoppd? If OE won't use a newer version no one else will since other platforms get the addons shipped with Kodi itself.

**Comment by opdenkamp** [comment]
There are a lot more distributions out there that we don't control. There's more out there than just Ubuntu, Windows, etc. One of the big advantages of separating core from stuff like this is that add-ons can still be fixed, even though development of core has moved to a new version.

That being said, I don't care much if you merge this or not, just commenting on the reasons that you're giving for not merging ;)

**Comment by Jalle19** [comment]
@opdenkamp which platforms would that be? As far as I know, OE is the only one with a repository for binary addons.

**Comment by opdenkamp** [comment]
e.g. any Linux distribution that's not called Ubuntu?

**Comment by Jalle19** [comment]
Okay. Let's wait a bit longer before we start backporting stuff in case any fixes show up at the last minute.

**Comment by CvH** [comment]
@Jalle19 
latest/rescent "official" Isengard version is shipped at OE, if there is an update here it would be updated at OE. At least this is the plan ;)

**Comment by CvH** [comment]
@Jalle19 
any news on this for Isengard ?

**Comment by Jalle19** [comment]
Closing this since master has the fixes applied. I hope to be able to do some backports during the weekend.

**Pull request closed without merging**
