### PR TITLE
[Matrix] API change update / cleanups

### PR DESCRIPTION
**Pull request by AlwinEsch**
Related to xbmc/xbmc#17586 and to bring in after them.

### CODE REVIEW

**Review by ksooo — APPROVED** [review]

**Comment by phunkyfish** [comment]
I think maybe this one was to wait for the kodi change right?

**Comment by ksooo** [comment]
Oh, but looking at the XBMC PR, I cannot see any PVR add-on API change.

**Comment by phunkyfish** [comment]
Is it not the header file change. Maybe I’m mistaken.

**Comment by AlwinEsch** [comment]
Ups, not seen that this was gone in, was thought to bring in after the Kodi request.
There is a very big API change inside (change of function table from `.` to `->`. Not direct much to change on addons, but need a recompile after them.

See this https://github.com/xbmc/xbmc/pull/17586/commits/9c118a8da45f8b7afe0e147e3576c59c59b6edec, specially on `xbmc_pvr_dll.h`

**Comment by ksooo** [comment]
Oh, sorry. My bad. Then we need another version bump for this add-on once the xmbc pr went in.

**Pull request merged**
