### PR TITLE
api 5.4.0 - drop SwitchChannel

### PR DESCRIPTION
**Pull request by FernetMenta**
https://github.com/xbmc/xbmc/pull/12552

### CODE REVIEW

**Comment by Jalle19** [comment]
So only OpenLiveStream will be used from now on?

**Comment by FernetMenta** [comment]
right, SwitchChannel is not called anymore in Kodi master

**Comment by Jalle19** [comment]
Alright, thanks

**Comment by ksooo** [comment]
As https://github.com/xbmc/xbmc/pull/12552 is now in, this one should go in as well.

**Pull request merged**
