### PR TITLE
Fix addon requiring restart no matter what settings are changed

### PR DESCRIPTION
**Pull request by Jalle19**
Two issues at play here:

* we use `type="number"` for the port settings, but without `option="int"`, the current value is sent to `ADDON_SetSetting` as a `float*` instead of `int*`, causing the comparison to fail inevitably. Changing the type to `integer` doesn't work either (even though it should), with that type the setting is not displayed in the dialog at all. See https://github.com/xbmc/xbmc/blob/master/xbmc/addons/AddonDll.h#L519

* the macro that compares if a string setting has changed was wrong, it did the exact opposite of what it was supposed to do.

@ksooo ping, and would also be great if you could runtime test this (I haven't tested at all but the changes worked fine for another addon I'm working on).

### CODE REVIEW

**Comment by ksooo** [comment]
... and what is fixed by this? Title implies that now changes to http and htsp port do no longer require a restart of the addon, right?

**Comment by Jalle19** [comment]
Yes that's what it fixes, I guess I didn't make it clear.

**Comment by ksooo** [comment]
@Jalle19 will take a look when back from Easter holidays...

**Comment by Jalle19** [comment]
@ksooo did you get a chance to take a look at this?

**Comment by ksooo** [comment]
@Jalle19 Not yet, sorry. I have always a bad feeling about this "it fixes stuff, but don't know why..."

**Comment by Jalle19** [comment]
@ksooo it's the string comparison I'm not sure about, the other commit is very much valid. I suspect the strings may appear non-equal due to missing null terminator or something like that.

**Comment by Jalle19** [comment]
@ksooo @opdenkamp I found the actual error

**Comment by ksooo** [comment]
Cool. What is it? Does it influence this PR?

**Comment by Jalle19** [comment]
@ksooo see the last commit

**Comment by ksooo** [comment]
@jalle19 hehe. Good catch. Will runtime test tonight (hopefully).

**Comment by ksooo** [comment]
@Jalle19 runtime tested. Seems to work nicely. Thus, :+1: from my side.

**Pull request merged**
