### PR TITLE
Fix crash on initial predictive tuning

### PR DESCRIPTION
**Pull request by nfedera**
Jarvis backport of commit 66b07a8a0f8aa7e65542a272fc1702e5d34e6269

### CODE REVIEW

**Comment by nfedera** [comment]
IMO the Travis cmake comand line requires `-DADDON_SRC_PREFIX=../../../..` instead of `-DADDON_SRC_PREFIX=../..`

**Comment by Jalle19** [comment]
@nfedera the build was changed recently so it broke all older branches. @ksooo still good to go?

**Comment by ksooo** [comment]
we should fix travis (cannot merge if failed, as this test is marked as required)

**Comment by nfedera** [comment]
good to go now ?

**Comment by ksooo** [comment]
Seems to work, but any reason for not doing it like in master? => https://github.com/kodi-pvr/pvr.hts/blob/master/.travis.yml#L45

**Comment by nfedera** [comment]
@ksooo sure, I've adapted the travis config from master

**Comment by ksooo** [comment]
Thanks.

**Pull request merged**
