### PR TITLE
Code cleanup: Apply Kodi clang-format ruleset.

### PR DESCRIPTION
**Pull request by ksooo**
I thought it was time to apply Kodi coding guidelines to pvr.hts. No functional changes, just code reshuffling.

@Jalle19 what do you think?

### CODE REVIEW

**Comment by phunkyfish** [comment]
Did you run clang-format on everything? I spotted there are still functions with void param: e.g. `myFunc(void)`.

Just wondering if that’s not working with clang format.

**Comment by ksooo** [comment]
Yes, applied clang-format file from you PR to src/*

**Comment by phunkyfish** [comment]
Cool, let me figure out how to get it to remove void and you can rerun.

**Comment by phunkyfish** [comment]
Ok, it can’t change `myFunc(void)` to `myFunc()`.

You need to make that change separately.

**Comment by ksooo** [comment]
Okay, thanks for the information.

**Review by Jalle19 — APPROVED** [review]

**Pull request merged**
